# Generated by Django 3.2.3 on 2022-02-16 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calci_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_eval', models.DateTimeField(auto_now_add=True)),
                ('expr', models.CharField(max_length=200)),
                ('result', models.DecimalField(decimal_places=5, max_digits=50)),
                ('expr_id', models.CharField(max_length=200, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calci_app.client')),
            ],
        ),
    ]
